export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const HOMEPAGE_NEXT = 'HOMEPAGE_NEXT';
export const HOMEPAGE_PREVIOUS = 'HOMEPAGE_PREVIOUS';
export const FETCH_LIST = 'FETCH_LIST';
export const UPDATE_VEHICLE_LIST = 'UPDATE_VEHICLE_LIST';